# Bevel Choice Behavior Notebook

In [1]:
#imports
import os
import glob
import pandas as pd
import numpy as np

For one file... import data

In [35]:
path = '/Users/jennygilbert/Documents/bevel_choice_computations/by_participant_txtfiles'
print(path)

df = pd.read_csv(os.path.join(path,'01.txt'), sep='\t', header = None, names = ['ID','run','img_pair','choice','side','outcome','matched','RT'])
print(df)

/Users/jennygilbert/Documents/bevel_choice_computations/by_participant_txtfiles
     ID    run img_pair choice  side outcome     matched        RT
0     1  run01       EF      F     1  reward  mismatched  1.569796
1     1  run01       CD      D     2  punish     matched  1.601124
2     1  run01       CD      D     2  punish     matched  1.600702
3     1  run01       CD   Miss  Miss    Miss        Miss      Miss
4     1  run01       AB      A     2  reward     matched  1.580793
5     1  run01       AB      B     2  reward  mismatched  1.564219
6     1  run01       AB      B     1  punish     matched  1.612839
7     1  run01       CD      D     2  punish     matched  1.594208
8     1  run01       CD      C     1  reward     matched  1.611155
9     1  run01       AB      A     1  punish  mismatched  1.594223
10    1  run01       EF      F     2  reward  mismatched  1.593177
11    1  run01       CD      D     2  punish     matched  1.590463
12    1  run01       AB      A     2  punish  mismatched  1.590193
13    1  run01       CD      C     1  reward     matched  1.605062
14    1  run01       CD      C     1  reward     matched  1.605347
15    1  run01       AB      A     1  punish  mismatched  1.587054
16    1  run01       CD      D     1  punish     matched  1.602987
17    1  run01       AB      A     1  reward     matched  1.602018
18    1  run01       AB      B     2  punish     matched  1.600867
19    1  run01       EF      E     2  reward     matched  1.582977
20    1  run01       AB   Miss  Miss    Miss        Miss      Miss
21    1  run01       AB      A     2  reward     matched  1.614960
22    1  run01       AB      B     1  reward  mismatched  1.580498
23    1  run01       CD      C     2  reward     matched  1.596363
24    1  run01       AB      A     1  reward     matched  1.596714
25    1  run01       CD   Miss  Miss    Miss        Miss      Miss
26    1  run02       EF      F     1  reward  mismatched  1.567948
27    1  run02       CD      D     1  reward  mismatched  1.583463
28    1  run02       AB      A     1  reward     matched  1.600016
29    1  run02       AB      B     2  punish     matched  1.599418
..   ..    ...      ...    ...   ...     ...         ...       ...
74    1  run03       AB      A     2  reward     matched  1.600248
75    1  run03       CD      C     2  reward     matched  1.615614
76    1  run03       AB      B     2  reward  mismatched  1.609683
77    1  run03       AB      B     1  punish     matched  1.609303
78    1  run04       AB      A     1  reward     matched  1.567914
79    1  run04       CD      C     2  punish  mismatched  1.566817
80    1  run04       AB      A     1  reward     matched  1.600015
81    1  run04       EF      E     2  punish  mismatched  1.597668
82    1  run04       EF      F     2  reward  mismatched  1.579999
83    1  run04       EF      F     2  punish     matched  1.579331
84    1  run04       AB      A     1  reward     matched  1.595599
85    1  run04       CD      C     1  reward     matched  1.610148
86    1  run04       AB      B     2  punish     matched  1.593779
87    1  run04       AB      B     2  punish     matched  1.592215
88    1  run04       CD   Miss  Miss    Miss        Miss      Miss
89    1  run04       CD   Miss  Miss    Miss        Miss      Miss
90    1  run04       EF      E     2  reward     matched  1.571638
91    1  run04       EF      F     1  reward  mismatched  1.603959
92    1  run04       EF      E     2  punish  mismatched  1.586667
93    1  run04       AB      A     2  reward     matched  1.602250
94    1  run04       CD      C     1  reward     matched  1.602497
95    1  run04       AB      B     2  punish     matched  1.583664
96    1  run04       CD      C     1  reward     matched  1.600436
97    1  run04       AB      B     2  reward  mismatched  1.582885
98    1  run04       CD      D     1  reward  mismatched  1.598864
99    1  run04       AB   Miss  Miss    Miss        Miss      Miss
100   1  run04       AB      B     2  punish     matched  1.596398
101   1  run04       CD      D     2  punish     matched  1.610596
102   1  run04       AB      A     2  reward     matched  1.576546
103   1  run04       AB      A     2  reward     matched  1.608679

[104 rows x 8 columns]

In [36]:
#Goal = calculate probability of each shape as the sum of number of previous rewards/sum of number of previous reinforcers
#running matched/total reinforcers = A prob of correct
#running mismatched/total reinforcers = B prob of being correct

#df.loc[(df.choice == 'A') & (df.outcome == 'reward'), 'a_rewarded'] = '1' 
#df.loc[(df.choice == 'A') & (df.outcome == 'punish'), 'a_rewarded'] = '0' 
#df.loc[(df.choice == 'B') & (df.outcome == 'reward'), 'b_rewarded'] = '1' 
#df.loc[(df.choice == 'B') & (df.outcome == 'punish'), 'b_rewarded'] = '0' 
#df.loc[(df.img_pair == 'AB') & (df.outcome != 'Miss'), 'ab_reinforcer_count'] = '1' 
#print(df)

#Split df into AB
df1 = df[df['img_pair'] == 'AB']
df1

     ID    run img_pair choice  side outcome     matched        RT
4     1  run01       AB      A     2  reward     matched  1.580793
5     1  run01       AB      B     2  reward  mismatched  1.564219
6     1  run01       AB      B     1  punish     matched  1.612839
9     1  run01       AB      A     1  punish  mismatched  1.594223
12    1  run01       AB      A     2  punish  mismatched  1.590193
15    1  run01       AB      A     1  punish  mismatched  1.587054
17    1  run01       AB      A     1  reward     matched  1.602018
18    1  run01       AB      B     2  punish     matched  1.600867
20    1  run01       AB   Miss  Miss    Miss        Miss      Miss
21    1  run01       AB      A     2  reward     matched  1.614960
22    1  run01       AB      B     1  reward  mismatched  1.580498
24    1  run01       AB      A     1  reward     matched  1.596714
28    1  run02       AB      A     1  reward     matched  1.600016
29    1  run02       AB      B     2  punish     matched  1.599418
34    1  run02       AB      A     2  reward     matched  1.594216
36    1  run02       AB      B     2  punish     matched  1.607863
39    1  run02       AB      B     2  reward  mismatched  1.587784
40    1  run02       AB      A     2  reward     matched  1.604879
41    1  run02       AB      A     2  reward     matched  1.586674
52    1  run03       AB      A     2  reward     matched  1.583751
53    1  run03       AB      B     1  punish     matched  1.615984
56    1  run03       AB      B     2  punish     matched  1.620375
57    1  run03       AB      B     2  reward  mismatched  1.613717
60    1  run03       AB      B     2  punish     matched  1.610023
62    1  run03       AB      A     2  punish  mismatched  1.595104
63    1  run03       AB      B     2  punish     matched  1.607097
69    1  run03       AB      B     2  punish     matched  1.598565
71    1  run03       AB      B     2  punish     matched  1.596828
74    1  run03       AB      A     2  reward     matched  1.600248
76    1  run03       AB      B     2  reward  mismatched  1.609683
77    1  run03       AB      B     1  punish     matched  1.609303
78    1  run04       AB      A     1  reward     matched  1.567914
80    1  run04       AB      A     1  reward     matched  1.600015
84    1  run04       AB      A     1  reward     matched  1.595599
86    1  run04       AB      B     2  punish     matched  1.593779
87    1  run04       AB      B     2  punish     matched  1.592215
93    1  run04       AB      A     2  reward     matched  1.602250
95    1  run04       AB      B     2  punish     matched  1.583664
97    1  run04       AB      B     2  reward  mismatched  1.582885
99    1  run04       AB   Miss  Miss    Miss        Miss      Miss
100   1  run04       AB      B     2  punish     matched  1.596398
102   1  run04       AB      A     2  reward     matched  1.576546
103   1  run04       AB      A     2  reward     matched  1.608679

In [41]:
cond = (df1.matched == 'matched')
#print(cond)
df1['matched_running'] = cond.cumsum().where(cond, 0).astype(int)
df1

cond1 = (df1.matched == 'mismatched')
#print(cond)
df1['mismatched_running'] = cond1.cumsum().where(cond1, 0).astype(int)
df1

cond2 = (df1.matched != 'Miss')
#print(cond)
df1['reinforcer_running'] = cond2.cumsum().where(cond2, 0).astype(int)
df1

df1['a_corr_prob'] = df1.matched_running / df1.reinforcer_running
df1['b_corr_prob'] = df1.mismatched_running / df1.reinforcer_running
df1

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,ID,run,img_pair,choice,side,outcome,matched,RT,matched_running,mismatched_running,reinforcer_running,a_corr_prob,b_corr_prob
4,1,run01,AB,A,2,reward,matched,1.580793,1,0,1,1.000000,0.000000
5,1,run01,AB,B,2,reward,mismatched,1.564219,0,1,2,0.000000,0.500000
6,1,run01,AB,B,1,punish,matched,1.612839,2,0,3,0.666667,0.000000
9,1,run01,AB,A,1,punish,mismatched,1.594223,0,2,4,0.000000,0.500000
12,1,run01,AB,A,2,punish,mismatched,1.590193,0,3,5,0.000000,0.600000
15,1,run01,AB,A,1,punish,mismatched,1.587054,0,4,6,0.000000,0.666667
17,1,run01,AB,A,1,reward,matched,1.602018,3,0,7,0.428571,0.000000
18,1,run01,AB,B,2,punish,matched,1.600867,4,0,8,0.500000,0.000000
20,1,run01,AB,Miss,Miss,Miss,Miss,Miss,0,0,0,NaN,NaN
21,1,run01,AB,A,2,reward,matched,1.614960,5,0,9,0.555556,0.000000
22,1,run01,AB,B,1,reward,mismatched,1.580498,0,5,10,0.000000,0.500000
24,1,run01,AB,A,1,reward,matched,1.596714,6,0,11,0.545455,0.000000
28,1,run02,AB,A,1,reward,matched,1.600016,7,0,12,0.583333,0.000000
29,1,run02,AB,B,2,punish,matched,1.599418,8,0,13,0.615385,0.000000
34,1,run02,AB,A,2,reward,matched,1.594216,9,0,14,0.642857,0.000000
36,1,run02,AB,B,2,punish,matched,1.607863,10,0,15,0.666667,0.000000
39,1,run02,AB,B,2,reward,mismatched,1.587784,0,6,16,0.000000,0.375000
40,1,run02,AB,A,2,reward,matched,1.604879,11,0,17,0.647059,0.000000
41,1,run02,AB,A,2,reward,matched,1.586674,12,0,18,0.666667,0.000000
52,1,run03,AB,A,2,reward,matched,1.583751,13,0,19,0.684211,0.000000
53,1,run03,AB,B,1,punish,matched,1.615984,14,0,20,0.700000,0.000000
56,1,run03,AB,B,2,punish,matched,1.620375,15,0,21,0.714286,0.000000
57,1,run03,AB,B,2,reward,mismatched,1.613717,0,7,22,0.000000,0.318182
60,1,run03,AB,B,2,punish,matched,1.610023,16,0,23,0.695652,0.000000
62,1,run03,AB,A,2,punish,mismatched,1.595104,0,8,24,0.000000,0.333333
63,1,run03,AB,B,2,punish,matched,1.607097,17,0,25,0.680000,0.000000
69,1,run03,AB,B,2,punish,matched,1.598565,18,0,26,0.692308,0.000000
71,1,run03,AB,B,2,punish,matched,1.596828,19,0,27,0.703704,0.000000
74,1,run03,AB,A,2,reward,matched,1.600248,20,0,28,0.714286,0.000000
76,1,run03,AB,B,2,reward,mismatched,1.609683,0,9,29,0.000000,0.310345
77,1,run03,AB,B,1,punish,matched,1.609303,21,0,30,0.700000,0.000000
78,1,run04,AB,A,1,reward,matched,1.567914,22,0,31,0.709677,0.000000
80,1,run04,AB,A,1,reward,matched,1.600015,23,0,32,0.718750,0.000000
84,1,run04,AB,A,1,reward,matched,1.595599,24,0,33,0.727273,0.000000
86,1,run04,AB,B,2,punish,matched,1.593779,25,0,34,0.735294,0.000000
87,1,run04,AB,B,2,punish,matched,1.592215,26,0,35,0.742857,0.000000
93,1,run04,AB,A,2,reward,matched,1.602250,27,0,36,0.750000,0.000000
95,1,run04,AB,B,2,punish,matched,1.583664,28,0,37,0.756757,0.000000
97,1,run04,AB,B,2,reward,mismatched,1.582885,0,10,38,0.000000,0.263158
99,1,run04,AB,Miss,Miss,Miss,Miss,Miss,0,0,0,NaN,NaN
100,1,run04,AB,B,2,punish,matched,1.596398,29,0,39,0.743590,0.000000
102,1,run04,AB,A,2,reward,matched,1.576546,30,0,40,0.750000,0.000000
103,1,run04,AB,A,2,reward,matched,1.608679,31,0,41,0.756098,0.000000