In [1]:
import os
import glob
import pandas as pd
import numpy as np
import pdb

basepath='/Users/jennygilbert/Documents/bevel_choice/by_participant_txtfiles'
os.chdir(basepath)

In [2]:
df = pd.read_csv(os.path.join(basepath,'01.txt'), sep='\t', header = None, names = ['ID','run','img_pair','choice','side','outcome','matched','RT'])
df1 = df[df['img_pair'] == 'AB'] 
df1

     ID    run img_pair choice  side outcome     matched        RT
4     1  run01       AB      A     2  reward     matched  1.580793
5     1  run01       AB      B     2  reward  mismatched  1.564219
6     1  run01       AB      B     1  punish     matched  1.612839
9     1  run01       AB      A     1  punish  mismatched  1.594223
12    1  run01       AB      A     2  punish  mismatched  1.590193
15    1  run01       AB      A     1  punish  mismatched  1.587054
17    1  run01       AB      A     1  reward     matched  1.602018
18    1  run01       AB      B     2  punish     matched  1.600867
20    1  run01       AB   Miss  Miss    Miss        Miss      Miss
21    1  run01       AB      A     2  reward     matched  1.614960
22    1  run01       AB      B     1  reward  mismatched  1.580498
24    1  run01       AB      A     1  reward     matched  1.596714
28    1  run02       AB      A     1  reward     matched  1.600016
29    1  run02       AB      B     2  punish     matched  1.599418
34    1  run02       AB      A     2  reward     matched  1.594216
36    1  run02       AB      B     2  punish     matched  1.607863
39    1  run02       AB      B     2  reward  mismatched  1.587784
40    1  run02       AB      A     2  reward     matched  1.604879
41    1  run02       AB      A     2  reward     matched  1.586674
52    1  run03       AB      A     2  reward     matched  1.583751
53    1  run03       AB      B     1  punish     matched  1.615984
56    1  run03       AB      B     2  punish     matched  1.620375
57    1  run03       AB      B     2  reward  mismatched  1.613717
60    1  run03       AB      B     2  punish     matched  1.610023
62    1  run03       AB      A     2  punish  mismatched  1.595104
63    1  run03       AB      B     2  punish     matched  1.607097
69    1  run03       AB      B     2  punish     matched  1.598565
71    1  run03       AB      B     2  punish     matched  1.596828
74    1  run03       AB      A     2  reward     matched  1.600248
76    1  run03       AB      B     2  reward  mismatched  1.609683
77    1  run03       AB      B     1  punish     matched  1.609303
78    1  run04       AB      A     1  reward     matched  1.567914
80    1  run04       AB      A     1  reward     matched  1.600015
84    1  run04       AB      A     1  reward     matched  1.595599
86    1  run04       AB      B     2  punish     matched  1.593779
87    1  run04       AB      B     2  punish     matched  1.592215
93    1  run04       AB      A     2  reward     matched  1.602250
95    1  run04       AB      B     2  punish     matched  1.583664
97    1  run04       AB      B     2  reward  mismatched  1.582885
99    1  run04       AB   Miss  Miss    Miss        Miss      Miss
100   1  run04       AB      B     2  punish     matched  1.596398
102   1  run04       AB      A     2  reward     matched  1.576546
103   1  run04       AB      A     2  reward     matched  1.608679

In [3]:
count = df1.choice.count()
list = np.arange(0, count)
list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42])

In [4]:
df1["matched_count"] = ""
df1["running_matched_count"] = ""

for i in list: 
    if df1.iloc[i, 6] == "matched":
        df1.iloc[i, 8] = 1
    
    elif df1.iloc[i, 6] == "mismatched":
        df1.iloc [i, 8] = 0
    else: 
        df1.iloc[i, 8] = 0
df1

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

,ID,run,img_pair,choice,side,outcome,matched,RT,matched_count,running_matched_count
4,1,run01,AB,A,2,reward,matched,1.580793,1,
5,1,run01,AB,B,2,reward,mismatched,1.564219,0,
6,1,run01,AB,B,1,punish,matched,1.612839,1,
9,1,run01,AB,A,1,punish,mismatched,1.594223,0,
12,1,run01,AB,A,2,punish,mismatched,1.590193,0,
15,1,run01,AB,A,1,punish,mismatched,1.587054,0,
17,1,run01,AB,A,1,reward,matched,1.602018,1,
18,1,run01,AB,B,2,punish,matched,1.600867,1,
20,1,run01,AB,Miss,Miss,Miss,Miss,Miss,0,
21,1,run01,AB,A,2,reward,matched,1.614960,1,
22,1,run01,AB,B,1,reward,mismatched,1.580498,0,
24,1,run01,AB,A,1,reward,matched,1.596714,1,
28,1,run02,AB,A,1,reward,matched,1.600016,1,
29,1,run02,AB,B,2,punish,matched,1.599418,1,
34,1,run02,AB,A,2,reward,matched,1.594216,1,
36,1,run02,AB,B,2,punish,matched,1.607863,1,
39,1,run02,AB,B,2,reward,mismatched,1.587784,0,
40,1,run02,AB,A,2,reward,matched,1.604879,1,
41,1,run02,AB,A,2,reward,matched,1.586674,1,
52,1,run03,AB,A,2,reward,matched,1.583751,1,
53,1,run03,AB,B,1,punish,matched,1.615984,1,
56,1,run03,AB,B,2,punish,matched,1.620375,1,
57,1,run03,AB,B,2,reward,mismatched,1.613717,0,
60,1,run03,AB,B,2,punish,matched,1.610023,1,
62,1,run03,AB,A,2,punish,mismatched,1.595104,0,
63,1,run03,AB,B,2,punish,matched,1.607097,1,
69,1,run03,AB,B,2,punish,matched,1.598565,1,
71,1,run03,AB,B,2,punish,matched,1.596828,1,
74,1,run03,AB,A,2,reward,matched,1.600248,1,
76,1,run03,AB,B,2,reward,mismatched,1.609683,0,
77,1,run03,AB,B,1,punish,matched,1.609303,1,
78,1,run04,AB,A,1,reward,matched,1.567914,1,
80,1,run04,AB,A,1,reward,matched,1.600015,1,
84,1,run04,AB,A,1,reward,matched,1.595599,1,
86,1,run04,AB,B,2,punish,matched,1.593779,1,
87,1,run04,AB,B,2,punish,matched,1.592215,1,
93,1,run04,AB,A,2,reward,matched,1.602250,1,
95,1,run04,AB,B,2,punish,matched,1.583664,1,
97,1,run04,AB,B,2,reward,mismatched,1.582885,0,
99,1,run04,AB,Miss,Miss,Miss,Miss,Miss,0,
100,1,run04,AB,B,2,punish,matched,1.596398,1,
102,1,run04,AB,A,2,reward,matched,1.576546,1,
103,1,run04,AB,A,2,reward,matched,1.608679,1,

In [21]:
df1["running_matched_count"] = df1["matched_count"].cumsum()

In [22]:
df1

,ID,run,img_pair,choice,side,outcome,matched,RT,matched_count,running_matched_count,reinforcer_running
4,1,run01,AB,A,2,reward,matched,1.580793,1,1,1.0
5,1,run01,AB,B,2,reward,mismatched,1.564219,0,1,2.0
6,1,run01,AB,B,1,punish,matched,1.612839,1,2,3.0
9,1,run01,AB,A,1,punish,mismatched,1.594223,0,2,4.0
12,1,run01,AB,A,2,punish,mismatched,1.590193,0,2,5.0
15,1,run01,AB,A,1,punish,mismatched,1.587054,0,2,6.0
17,1,run01,AB,A,1,reward,matched,1.602018,1,3,7.0
18,1,run01,AB,B,2,punish,matched,1.600867,1,4,8.0
20,1,run01,AB,Miss,Miss,Miss,Miss,Miss,0,4,NaN
21,1,run01,AB,A,2,reward,matched,1.614960,1,5,9.0
22,1,run01,AB,B,1,reward,mismatched,1.580498,0,5,10.0
24,1,run01,AB,A,1,reward,matched,1.596714,1,6,11.0
28,1,run02,AB,A,1,reward,matched,1.600016,1,7,12.0
29,1,run02,AB,B,2,punish,matched,1.599418,1,8,13.0
34,1,run02,AB,A,2,reward,matched,1.594216,1,9,14.0
36,1,run02,AB,B,2,punish,matched,1.607863,1,10,15.0
39,1,run02,AB,B,2,reward,mismatched,1.587784,0,10,16.0
40,1,run02,AB,A,2,reward,matched,1.604879,1,11,17.0
41,1,run02,AB,A,2,reward,matched,1.586674,1,12,18.0
52,1,run03,AB,A,2,reward,matched,1.583751,1,13,19.0
53,1,run03,AB,B,1,punish,matched,1.615984,1,14,20.0
56,1,run03,AB,B,2,punish,matched,1.620375,1,15,21.0
57,1,run03,AB,B,2,reward,mismatched,1.613717,0,15,22.0
60,1,run03,AB,B,2,punish,matched,1.610023,1,16,23.0
62,1,run03,AB,A,2,punish,mismatched,1.595104,0,16,24.0
63,1,run03,AB,B,2,punish,matched,1.607097,1,17,25.0
69,1,run03,AB,B,2,punish,matched,1.598565,1,18,26.0
71,1,run03,AB,B,2,punish,matched,1.596828,1,19,27.0
74,1,run03,AB,A,2,reward,matched,1.600248,1,20,28.0
76,1,run03,AB,B,2,reward,mismatched,1.609683,0,20,29.0
77,1,run03,AB,B,1,punish,matched,1.609303,1,21,30.0
78,1,run04,AB,A,1,reward,matched,1.567914,1,22,31.0
80,1,run04,AB,A,1,reward,matched,1.600015,1,23,32.0
84,1,run04,AB,A,1,reward,matched,1.595599,1,24,33.0
86,1,run04,AB,B,2,punish,matched,1.593779,1,25,34.0
87,1,run04,AB,B,2,punish,matched,1.592215,1,26,35.0
93,1,run04,AB,A,2,reward,matched,1.602250,1,27,36.0
95,1,run04,AB,B,2,punish,matched,1.583664,1,28,37.0
97,1,run04,AB,B,2,reward,mismatched,1.582885,0,28,38.0
99,1,run04,AB,Miss,Miss,Miss,Miss,Miss,0,28,NaN
100,1,run04,AB,B,2,punish,matched,1.596398,1,29,39.0
102,1,run04,AB,A,2,reward,matched,1.576546,1,30,40.0
103,1,run04,AB,A,2,reward,matched,1.608679,1,31,41.0

In [23]:
cond2 = (df1.matched != 'Miss')
df1['reinforcer_running'] = cond2.cumsum().where(cond2, 999).astype(int)

df1 = df1.replace(999,np.NaN)

df1['a_learnedprob_correct'] = df1.running_matched_count / df1.reinforcer_running
df1['b_learnedprob_correct'] = 1 - df1.a_learnedprob_correct
df1

,ID,run,img_pair,choice,side,outcome,matched,RT,matched_count,running_matched_count,reinforcer_running,a_learnedprob_correct,b_learnedprob_correct
4,1,run01,AB,A,2,reward,matched,1.580793,1,1,1.0,1.000000,0.000000
5,1,run01,AB,B,2,reward,mismatched,1.564219,0,1,2.0,0.500000,0.500000
6,1,run01,AB,B,1,punish,matched,1.612839,1,2,3.0,0.666667,0.333333
9,1,run01,AB,A,1,punish,mismatched,1.594223,0,2,4.0,0.500000,0.500000
12,1,run01,AB,A,2,punish,mismatched,1.590193,0,2,5.0,0.400000,0.600000
15,1,run01,AB,A,1,punish,mismatched,1.587054,0,2,6.0,0.333333,0.666667
17,1,run01,AB,A,1,reward,matched,1.602018,1,3,7.0,0.428571,0.571429
18,1,run01,AB,B,2,punish,matched,1.600867,1,4,8.0,0.500000,0.500000
20,1,run01,AB,Miss,Miss,Miss,Miss,Miss,0,4,NaN,NaN,NaN
21,1,run01,AB,A,2,reward,matched,1.614960,1,5,9.0,0.555556,0.444444
22,1,run01,AB,B,1,reward,mismatched,1.580498,0,5,10.0,0.500000,0.500000
24,1,run01,AB,A,1,reward,matched,1.596714,1,6,11.0,0.545455,0.454545
28,1,run02,AB,A,1,reward,matched,1.600016,1,7,12.0,0.583333,0.416667
29,1,run02,AB,B,2,punish,matched,1.599418,1,8,13.0,0.615385,0.384615
34,1,run02,AB,A,2,reward,matched,1.594216,1,9,14.0,0.642857,0.357143
36,1,run02,AB,B,2,punish,matched,1.607863,1,10,15.0,0.666667,0.333333
39,1,run02,AB,B,2,reward,mismatched,1.587784,0,10,16.0,0.625000,0.375000
40,1,run02,AB,A,2,reward,matched,1.604879,1,11,17.0,0.647059,0.352941
41,1,run02,AB,A,2,reward,matched,1.586674,1,12,18.0,0.666667,0.333333
52,1,run03,AB,A,2,reward,matched,1.583751,1,13,19.0,0.684211,0.315789
53,1,run03,AB,B,1,punish,matched,1.615984,1,14,20.0,0.700000,0.300000
56,1,run03,AB,B,2,punish,matched,1.620375,1,15,21.0,0.714286,0.285714
57,1,run03,AB,B,2,reward,mismatched,1.613717,0,15,22.0,0.681818,0.318182
60,1,run03,AB,B,2,punish,matched,1.610023,1,16,23.0,0.695652,0.304348
62,1,run03,AB,A,2,punish,mismatched,1.595104,0,16,24.0,0.666667,0.333333
63,1,run03,AB,B,2,punish,matched,1.607097,1,17,25.0,0.680000,0.320000
69,1,run03,AB,B,2,punish,matched,1.598565,1,18,26.0,0.692308,0.307692
71,1,run03,AB,B,2,punish,matched,1.596828,1,19,27.0,0.703704,0.296296
74,1,run03,AB,A,2,reward,matched,1.600248,1,20,28.0,0.714286,0.285714
76,1,run03,AB,B,2,reward,mismatched,1.609683,0,20,29.0,0.689655,0.310345
77,1,run03,AB,B,1,punish,matched,1.609303,1,21,30.0,0.700000,0.300000
78,1,run04,AB,A,1,reward,matched,1.567914,1,22,31.0,0.709677,0.290323
80,1,run04,AB,A,1,reward,matched,1.600015,1,23,32.0,0.718750,0.281250
84,1,run04,AB,A,1,reward,matched,1.595599,1,24,33.0,0.727273,0.272727
86,1,run04,AB,B,2,punish,matched,1.593779,1,25,34.0,0.735294,0.264706
87,1,run04,AB,B,2,punish,matched,1.592215,1,26,35.0,0.742857,0.257143
93,1,run04,AB,A,2,reward,matched,1.602250,1,27,36.0,0.750000,0.250000
95,1,run04,AB,B,2,punish,matched,1.583664,1,28,37.0,0.756757,0.243243
97,1,run04,AB,B,2,reward,mismatched,1.582885,0,28,38.0,0.736842,0.263158
99,1,run04,AB,Miss,Miss,Miss,Miss,Miss,0,28,NaN,NaN,NaN
100,1,run04,AB,B,2,punish,matched,1.596398,1,29,39.0,0.743590,0.256410
102,1,run04,AB,A,2,reward,matched,1.576546,1,30,40.0,0.750000,0.250000
103,1,run04,AB,A,2,reward,matched,1.608679,1,31,41.0,0.756098,0.243902